---
engines:
  csslint:
    enabled: true
    exclude_paths:
    - "client/styles/one-dark.css"
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
- test-files/
- "webpack.config.dev.js"
- "webpack.config.prod.js"
